version: '3.9'

services:
  shopper:
    container_name: shopper
    image: shopper
    build:
      context: .
      dockerfile: Dockerfile
      tags:
        - shopper
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - $PORT:$PORT
